#!/bin/bash

apt-get update && apt-get upgrade >> /var/log/update_script.log
echo "apt-get update && apt-get upgrade >> /var/log/update_script.log" > /usr/local/bin/01.sh
echo '00 4 * * 1 /bin/sh /usr/local/bin/01.sh' | crontab

# https://awc.com.my/uploadnew/5ffbd639c5e6eccea359cb1453a02bed_Setting%20Up%20Cron%20Job%20Using%20crontab.pdf
